hostelmanager/urls.py
from django.conf.urls import url
from django.contrib import admin
from finder import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    url(r'^details/$',views.details,name="details"),
]

finder/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Hostels(models.Model) :
	HostelName = models.CharField(max_length=20,default='Select your Hostel',null=False)

	def __unicode__(self):
		return unicode(self.HostelName)


class Status(models.Model):
	StudentStatus = models.CharField(max_length=20,default=None,null=False)

	def __unicode__(self):
		return unicode(self.StudentStatus)		

class Student(models.Model) :
	name = models.CharField(max_length=50,default=None,null=False)
	RollNo = models.CharField(max_length=20,default=None,null=False)
	hostel = models.ForeignKey(Hostels,default=None,null=False)
	status = models.ForeignKey(Status,default=None,null=False)

	def __unicode__(self):
		return unicode(self.name)

finder/forms.py
from django import forms
from models import Student

class StudentForm(forms.ModelForm) :
	class Meta:
		model = Student
		fields = ['name','RollNo','hostel','status']
		

finder/views.py
w# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from models import Student,Hostels,Status
from django.views.generic import View
from forms import StudentForm
# from forms import StudentForm

# Create your views here.
def index(request) :
	form = StudentForm(request.POST)
	if(request.method=='POST'):
		if(form.is_valid()):
			form.save()
			message = 'Successfully Registered'
			return render(request,'details.html',{'message': message})

		else :
			form_error = "(Registration Failed. Have you filled all the details?)"
			return render(request,'index.html',{'form': form,'form_error': form_error})
	else :
		form = StudentForm(request.POST)
	return render(request,'index.html',{'form': form})

def details(request):
	object_list = Student.objects.all().order_by('status_id')
	bh1 = Student.objects.filter(hostel__id=1).order_by('status_id')
	bh2 = Student.objects.filter(hostel__id=2).order_by('status_id')
	bh3 = Student.objects.filter(hostel__id=3).order_by('status_id')
	bh4 = Student.objects.filter(hostel__id=4).order_by('status_id')
	gh1 = Student.objects.filter(hostel_id=5).order_by('status_id')
	gh2 = Student.objects.filter(hostel_id=6).order_by('status_id')

	return render(request,'detail.html',{'object_list':object_list,'bh1': bh1,'bh2': bh2,'bh3': bh3,'bh4': bh4,'gh1': gh1,'gh2': gh2,})

finder/templates/detail.html
<!-- 
<h2>Working</h2>
{% for field in bh3 %}
<p>BH3</p>
	<p>{{field.RollNo}}</p>
	<p>{{ field.name }}</p>
	<p>{{ field.status }}</p>
{% endfor %} -->


<html>
<head>
	<title>{% block title %}Hostel manager{% endblock %}</title>
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
	<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/tables.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/custom.css' %}" />
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<style>
	.navli .nava {
		color: white !important;
	}
	.navli:hover .nava:hover {
		color: #707677 !important;
	}
</style>

        
</head>


<body>


<nav class="navbar navbar-inverse"  style ="background-color: #55acee;font-family:monospace;border-color: #55acee">
    <div class="container-fluid">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#" style="color:white">Portal</a>
	</div>
	<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-left">
		<li class="navli">
			<a href="{% url 'index' %}" class="nava">	
				Register
			</a>
		</li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
		<li class="navli">
			<a href="#bh1" class="nava">	
				BH1
			</a>
		</li>
		<li class="navli">
			<a href="#bh2" class="nava">	
				BH2
			</a>
		</li>
		<li class="navli">
			<a href="#bh3" class="nava">	
				BH3
			</a>
		</li>
		<li class="navli">
			<a href="#bh4" class="nava">	
				BH4
			</a>
		</li>	
		<li class="navli">
			<a href="#gh1" class="nava">	
				GH1
			</a>
		</li>
		<li class="navli">
			<a href="#gh2" class="nava">	
				GH2
			</a>
		</li>

	</ul>
	

</nav>

<h3 style ="text-align: center;color: #55acee;font-family:monospace;">List of entries</h3><!--Form-->

	<div id="bh1">
		{% if bh1 %}
				
		        <h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 1</h2>   
				<table class="table-fill">
		    	<thead >
		    		<tr>
		    			<th class="text-center">RollNo.</th>
		    			<th class="text-center">Name</th>
		    			<th class="text-center">Status</th>
		    		</tr>
		    	</thead>
		    	<tbody class="table-hover">
		    		{% for student in bh1 %}
		    		<tr>
		    			<td class="text-center">{{student.RollNo}}</td>
		    			<td class="text-center"> {{student.name}}</td>
		    			<td class="text-center"> {{ student.status }}</td>
		    		</tr>

		    		{% endfor %}
		    	</tbody>
		    	</table>

		{% else %}
				<h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 1</h2> 
		        <p style="text-align:center;font-family:monospace;color: #55acee">(No registered entries from BH1)</p>
		{% endif %}
	</div>
	<div id="bh2">	

		{% if bh2 %}
				
		        <h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 2</h2>  
				<table class="table-fill">
		    	<thead >
		    		<tr>
		    			<th class="text-center">RollNo.</th>
		    			<th class="text-center">Name</th>
		    			<th class="text-center">Status</th>
		    		</tr>
		    	</thead>
		    	<tbody class="table-hover">
		    		{% for student in bh2 %}
		    		<tr>
		    			<td class="text-center">{{student.RollNo}}</td>
		    			<td class="text-center"> {{student.name}}</td>
		    			<td class="text-center"> {{ student.status }}</td>
		    		</tr>

		    		{% endfor %}
		    	</tbody>
		    	</table>
		{% else %}
				<h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 2</h2> 
		        <p style="text-align:center;font-family:monospace;color: #55acee">(No registered entries from BH2)</p>
		{% endif %}
	</div>
	<div id="bh3">
		{% if bh3 %}
				
		        <h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 3</h2>   
				<table class="table-fill">
		    	<thead >
		    		<tr>
		    			<th class="text-center">RollNo.</th>
		    			<th class="text-center">Name</th>
		    			<th class="text-center">Status</th>
		    		</tr>
		    	</thead>
		    	<tbody class="table-hover">
		    		{% for student in bh3 %}
		    		<tr>
		    			<td class="text-center">{{student.RollNo}}</td>
		    			<td class="text-center"> {{student.name}}</td>
		    			<td class="text-center"> {{ student.status }}</td>
		    		</tr>

		    		{% endfor %}
		    	</tbody>
		    </table>
		    	
		{% else %}
				<h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 3</h2> 
		        <p style="text-align:center;font-family:monospace;color: #55acee">(No registered entries from BH3)</p>
		{% endif %}
	</div>
	<div id="bh4">
		{% if bh4 %}
				
		        <h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 4</h2>  
				<table class="table-fill">
		    	<thead >
		    		<tr>
		    			<th class="text-center">RollNo.</th>
		    			<th class="text-center">Name</th>
		    			<th class="text-center">Status</th>
		    		</tr>
		    	</thead>
		    	<tbody class="table-hover">
		    		{% for student in bh4 %}
		    		<tr>
		    			<td class="text-center">{{student.RollNo}}</td>
		    			<td class="text-center"> {{student.name}}</td>
		    			<td class="text-center"> {{ student.status }}</td>
		    		</tr>

		    		{% endfor %}
		    	</tbody>
		    	</table>
		    	
		{% else %}
				<h2 style="text-align:center;font-family:monospace;color:#4D7F89">BH - 4</h2> 
		        <p style="text-align:center;font-family:monospace;color: #55acee">(No registered entries from BH4)</p>
		{% endif %}
	</div>
	<div id="gh1">
		{% if gh1 %}
				
		        <h2 style="text-align:center;font-family:monospace;color:#4D7F89">GH - 1</h2>  
				<table class="table-fill">
		    	<thead >
		    		<tr>
		    			<th class="text-center">RollNo.</th>
		    			<th class="text-center">Name</th>
		    			<th class="text-center">Status</th>
		    		</tr>
		    	</thead>
		    	<tbody class="table-hover">
		    		{% for student in gh1 %}
		    		<tr>
		    			<td class="text-center">{{student.RollNo}}</td>
		    			<td class="text-center"> {{student.name}}</td>
		    			<td class="text-center"> {{ student.status }}</td>
		    		</tr>

		    		{% endfor %}
		    	</tbody>
		    	</table>
		{% else %}
				<h2 style="text-align:center;font-family:monospace;color:#4D7F89">GH - 1</h2> 
		        <p style="text-align:center;font-family:monospace;color: #55acee">(No registered entries from GH1)</p>
		{% endif %}
	</div>
	<div id="gh2">
		{% if gh2 %}
				
		        <h2 style="text-align:center;font-family:monospace;color:#4D7F89">GH - 2</h2>  
				<table class="table-fill">
		    	<thead >
		    		<tr>
		    			<th class="text-center">RollNo.</th>
		    			<th class="text-center">Name</th>
		    			<th class="text-center">Status</th>
		    		</tr>
		    	</thead>
		    	<tbody class="table-hover">
		    		{% for student in gh2 %}
		    		<tr>
		    			<td class="text-center">{{student.RollNo}}</td>
		    			<td class="text-center"> {{student.name}}</td>
		    			<td class="text-center"> {{ student.status }}</td>
		    		</tr>

		    		{% endfor %}
		    	</tbody>
		    	</table> 
		{% else %}
				<h2 style="text-align:center;font-family:monospace;color:#4D7F89">GH - 2</h2> 
		        <p style="text-align:center;font-family:monospace;color: #55acee">(No registered entries from GH2)</p>

		{% endif %}
	</div>
<br><br>


</body>
</html>

</body> -->

finder/templates/index.html
<html>
<head>
	<title>{% block title %}Hostel manager{% endblock %}</title>
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
	<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/tables.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/custom.css' %}" />
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

        

<style>
	.navli .nava {
		color: white !important;
	}
	.navli:hover .nava:hover {
		color: #707677 !important;
	}
</style>

        
</head>


<body>


<nav class="navbar navbar-inverse"  style ="background-color: #55acee;font-family:monospace;border-color: #55acee">
    <div class="container">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#" style="color:white">Portal</a>
	</div>
	<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-right">

			

			<li class="navli">
				<a href="{% url 'details' %}" class="nava">	
					<span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp;
					View Entries
				</a>
			</li>
	</ul>
</div>
</nav>

<h3 style ="text-align: center;color: #55acee;font-family:monospace;">Fill in you details here</h3><!--Form-->
<p style ="text-align: center;color: #55acee;font-family:monospace;">{{form_error}}</p>
<p style ="text-align: center;color: #55acee;font-family:monospace;">(Your status should be "Available" if you haven't got a roomie yet)</p>
<div class="login-page">
  <div class="form">    
    <form class="login-form" method="POST" action="." role="form">
    	<p style ="text-align: center;color: #55acee;font-family:monospace;">All Fields are compulsory</p>
    	{% csrf_token %}
     <input id="id_name" type="text" placeholder="Name " name="name"/>
      <input id="id_RollNo" type="text" placeholder="Enrollment No." name="RollNo"/>
      
     
      		<p style="float:left;font-family:Monospace;color:#787A7A;">HOSTEL:</p>

      			<div style="font-family: Monospace">{{form.hostel}}</div>
   			
<br>

      		<p style="float:left;font-family:Monospace;color:#787A7A;">STATUS:</p>

      			{{form.status}}
<br><br>
      <div class="form-group"> 

      
      <button type='submit' class="center">Submit</button>
      
      
	</form>
	


  </div>
</div>
<br>
<br>

<div id="buttons" class="center">
  <a href="{% url 'details' %}" class="btnBottom blue" class="center"> View Entries</a>
</div>
<br><br>


{% if message %}
<script>
    alert('RegisteredSuccesfully');
</script>
{% endif %}

</body>
</html>

<!--  
<body>
 <h1>WElcome to the prject</h1>
   <form method="POST" action="" class="post-form">{% csrf_token %}
{{ form.as_p }}

        
{% for field in form %}
	{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
	<label>{{ field.label_tag }}</label>
	<div> {{ field }} </div>	
{% endfor %}

        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% if message %}
    <script>
    	alert('RegisteredSuccesfully')

    </script>
{% endif %}
</body> -->